### ISSUE TITLE
WTA rankings : Shannan McCarthy and an 'Unknown player' share the same WTA ID number

### ISSUE THREAD

**Issue by bazzaar** [JeffSackmann/tennis_wta#13]
Hi,

The wta rankings in this repo allocate the same wta id no. 201273 to #BOTH# Shannan McCarthy, and an 'Unknown player', consequently their rankings data are all mixed up. In actual fact, in the current repo, it only involves 5 ranking records from the 'Unknown player'.

I've been unable to find out who 'Unknown player' might be, for that I'd need to have access to the official weekly ranking lists between 1992-06-22 and 1992-07-20. Assuming someone is able to match the dates/rankings with a name, and wta id, these 5 records need to be re-assigned to that id.

The following records are the ones in this repo that need to be assigned to the correct wta id, as these specific records aren't Shannan McCarthy's (who I assume will retain the 201273 id). Shannan McCarthy's records are the remainder of the ones currently under the 201273 id, once the changes have been made.

-- assign the correct id to these --
1992-06-22,770,201273,0
1992-06-29,770,201273,0
1992-07-06,757,201273,0
1992-07-13,756,201273,0
1992-07-20,737,201273,0

I hope this helps.
bazzaar

**Comment by JeffSackmann** [comment]
turns out the unknown player is Shawn McCarthy:
https://www.wtatennis.com/players/130252/shawn-mccarthy/rankings-history

and for whatever reason, I don't have rankings past #800 for that time period. (that's how a player can have only five weeks of rankings -- she was outside the top 800 before and after that.) Now fixed -- only rankings, no results. Though per her WTA page, she did play Mary Pierce in an ITF qualifying match in 1990. (she lost)
